repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.0.0
    hooks:
      - id: seed-isort-config
        args: [--application-directories, 'iq_api']
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        args:
          - --max-line-length=140
