version: "3.5"
services:
  mongo:
    image: mongo
    container_name: IQ_mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - .volumes/mongo:/data/db
    env_file: .env
  api:
    build:
      context: ./iq-api
      dockerfile: Dockerfile
      target: runner
    container_name: IQ_api
    ports:
      - 80:80
    env_file: .env
  nginx:
    build: ./iq-client
    container_name: IQ_client
    restart: always
    ports:
      - 8002:80
    env_file: .env
