version: "3.5"
services:
  mongo:
    image: mongo
    container_name: IQ_standalone_mongo
    restart: always
    env_file: ../.env
    ports:
      - 27017:27017
    volumes:
      - ../.volumes/mongo:/data/db
